# Does the required kernel configuration for 
# Qualcomm StreamBoost
#
define KernelPackage/streamboost
  SUBMENU:=StreamBoost
  TITLE:=Qualcomm StreamBoost
  DEPENDS:=+kmod-sched +kmod-ipt-core +kmod-ipt-conntrack-extra \
	+kmod-nf-conntrack-netlink 
  KCONFIG:= \
	CONFIG_NETFILTER=y \
	CONFIG_IP_NF_TARGET_CONNMARK=y \
	CONFIG_NF_CT_NETLINK=y \
	CONFIG_NF_CONNTRACK=y \
	CONFIG_NF_CONNTRACK_MARK=y \
	CONFIG_NETFILTER_XTABLES=y \
	CONFIG_NETFILTER_XT_MARK=y \
	CONFIG_NETFILTER_XT_CONNMARK=y \
	CONFIG_NETFILTER_XT_TARGET_CLASSIFY=y \
	CONFIG_NETFILTER_XT_TARGET_CONNMARK=y \
	CONFIG_NETFILTER_XT_MATCH_STATE=y \
	CONFIG_NETFILTER_XT_MATCH_PHYSDEV=y \
	CONFIG_NETFILTER_XT_MATCH_CONNBYTES=y \
	CONFIG_NETFILTER_XT_MATCH_CONNLIMIT=y \
	CONFIG_NETFILTER_XT_MATCH_CONNMARK=y \
	CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y \
	CONFIG_NETFILTER_XT_MATCH_LIMIT=y \
	CONFIG_IP_NF_MANGLE=y
endef
$(eval $(call KernelPackage,streamboost))
