define KernelPackage/usb-touch
  SUBMENU:=USB Support
  TITLE:=Support for USB touch screens
  DEPENDS:=@USB_SUPPORT +kmod-usb-hid
  KCONFIG:=CONFIG_INPUT_TOUCHSCREEN=y \
	CONFIG_TOUCHSCREEN_USB_COMPOSITE \
	CONFIG_TOUCHSCREEN_USB_EGALAX \
	CONFIG_TOUCHSCREEN_USB_PANJIT \
	CONFIG_TOUCHSCREEN_USB_3M \
	CONFIG_TOUCHSCREEN_USB_ITM \
	CONFIG_TOUCHSCREEN_USB_ETURBO \
	CONFIG_TOUCHSCREEN_USB_GUNZE \
	CONFIG_TOUCHSCREEN_USB_DMC_TSC10 \
	CONFIG_TOUCHSCREEN_USB_IRTOUCH \
	CONFIG_TOUCHSCREEN_USB_IDEALTEK \
	CONFIG_TOUCHSCREEN_USB_GENERAL_TOUCH \
	CONFIG_TOUCHSCREEN_USB_GOTOP \
	CONFIG_TOUCHSCREEN_USB_JASTEC \
	CONFIG_TOUCHSCREEN_USB_E2I \
	CONFIG_TOUCHSCREEN_USB_ZYTRONIC \
	CONFIG_TOUCHSCREEN_USB_ETT_TC45USB \
	CONFIG_TOUCHSCREEN_USB_NEXIO
  FILES:=$(LINUX_DIR)/drivers/input/touchscreen/usbtouchscreen.ko
  AUTOLOAD:=$(call AutoLoad,21,usbtouchscreen)
endef

$(eval $(call KernelPackage,usb-touch))
